version: '3.7'

services:
  mysql: # AuroraDB uses MySQL, so, this service name is correct.
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: general
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./schemas/mysql/dml:/docker-entrypoint-initdb.d
